In [39]:
import pandas as pd
import numpy as np

In [40]:
df_copy = pd.read_csv('IPL.csv')

C:\Users\aksha\AppData\Local\Temp\ipykernel_19984\1931698479.py:1: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df_copy = pd.read_csv('IPL.csv')

In [41]:
df_copy.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,131972,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [42]:
df_copy.isnull().sum()

Unnamed: 0               0
match_id                 0
date                     0
match_type               0
event_name               0
                     ...
batter_balls             0
bowler_wicket            0
batting_partners         0
next_batter         264884
striker_out              0
Length: 64, dtype: int64

In [43]:
df_copy.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'batter_runs',
       'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter',
       'striker_out'],
      dtype='object')

In [44]:
df_copy=df_copy[df_copy['innings']==2]

In [45]:
df_copy.shape

(133903, 64)

In [46]:
drop_cols = [
    'Unnamed: 0', 'date', 'match_type', 'event_name',
    'bat_pos', 'bowler', 'batter',
    'runs_bowler', 'runs_not_boundary',
    'extra_type', 'non_striker', 'non_striker_pos',
    'wicket_kind', 'player_out', 'fielders',
    'review_batter', 'team_reviewed', 'review_decision',
    'umpire', 'umpires_call', 'player_of_match',
    'day', 'month', 'year', 'season',
    'gender', 'team_type', 'superover_winner',
    'result_type', 'method',
    'event_match_no', 'stage', 'match_number',
    'new_batter', 'batter_runs', 'batter_balls',
    'bowler_wicket', 'batting_partners',
    'next_batter', 'striker_out','win_outcome'
]

In [47]:
df_copy.drop(columns=drop_cols,inplace=True)

In [48]:
df_copy=df_copy.dropna(subset=['runs_target'])

In [49]:
df_copy.head()

,match_id,innings,batting_team,bowling_team,over,ball,ball_no,runs_batter,balls_faced,valid_ball,...,match_won_by,toss_winner,toss_decision,venue,city,balls_per_over,overs,team_runs,team_balls,team_wicket
124,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,0.1,1,1,1,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,6,20,1,1,0
125,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,0.2,0,0,0,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,6,20,2,1,0
126,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,0.2,0,1,1,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,6,20,2,2,0
127,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,0.3,1,1,1,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,6,20,3,3,0
128,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,0.4,1,1,1,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,6,20,4,4,0

In [50]:
df_copy['current_score']=df_copy['team_runs']
df_copy['balls_bowled']=df_copy['team_balls']
df_copy['wickets']=df_copy['team_wicket']

In [51]:
df_copy['balls_left']=120-df_copy['team_balls']
df_copy['runs_left']=df_copy['runs_target']-df_copy['team_runs']
df_copy['wickets_left']=10-df_copy['team_wicket']

In [52]:
df_copy['current_run_rate']=round(df_copy['team_runs']/(df_copy['team_balls']/6),2)
df_copy['required_run_rate']=round(df_copy['runs_left']/(df_copy['balls_left']/6),2)

In [53]:
df_copy=df_copy[df_copy['balls_left'] > 0]

In [54]:
df_copy.drop(columns=['team_runs', 'team_balls', 'team_wicket'],inplace=True)

In [55]:
df_copy.shape

(133456, 28)

In [56]:
df_copy.columns

Index(['match_id', 'innings', 'batting_team', 'bowling_team', 'over', 'ball',
       'ball_no', 'runs_batter', 'balls_faced', 'valid_ball', 'runs_extras',
       'runs_total', 'runs_target', 'match_won_by', 'toss_winner',
       'toss_decision', 'venue', 'city', 'balls_per_over', 'overs',
       'current_score', 'balls_bowled', 'wickets', 'balls_left', 'runs_left',
       'wickets_left', 'current_run_rate', 'required_run_rate'],
      dtype='object')

In [57]:
drop_more = [
    'runs_batter', 
    'balls_faced', 
    'valid_ball', 
    'runs_extras', 
    'runs_total'
]

df_copy=df_copy.drop(columns=drop_more)

In [58]:
df_copy=df_copy.drop(columns=['balls_per_over'])

In [59]:
df_copy.shape

(133456, 22)

In [60]:
df_copy.head()

,match_id,innings,batting_team,bowling_team,over,ball,ball_no,runs_target,match_won_by,toss_winner,...,city,overs,current_score,balls_bowled,wickets,balls_left,runs_left,wickets_left,current_run_rate,required_run_rate
124,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,0.1,223.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,Bangalore,20,1,1,0,119,222.0,10,6.0,11.19
125,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,0.2,223.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,Bangalore,20,2,1,0,119,221.0,10,12.0,11.14
126,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,0.2,223.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,Bangalore,20,2,2,0,118,221.0,10,6.0,11.24
127,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,0.3,223.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,Bangalore,20,3,3,0,117,220.0,10,6.0,11.28
128,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,0.4,223.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,Bangalore,20,4,4,0,116,219.0,10,6.0,11.33

In [61]:
df_copy['result']=(df_copy['batting_team']==df_copy['match_won_by']).astype(int)

In [62]:
df_copy.head()

,match_id,innings,batting_team,bowling_team,over,ball,ball_no,runs_target,match_won_by,toss_winner,...,overs,current_score,balls_bowled,wickets,balls_left,runs_left,wickets_left,current_run_rate,required_run_rate,result
124,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,0.1,223.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,20,1,1,0,119,222.0,10,6.0,11.19,0
125,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,0.2,223.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,20,2,1,0,119,221.0,10,12.0,11.14,0
126,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,0.2,223.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,20,2,2,0,118,221.0,10,6.0,11.24,0
127,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,0.3,223.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,20,3,3,0,117,220.0,10,6.0,11.28,0
128,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,0.4,223.0,Kolkata Knight Riders,Royal Challengers Bangalore,...,20,4,4,0,116,219.0,10,6.0,11.33,0

In [63]:
df_copy.drop('match_won_by',axis=1,inplace=True)

In [64]:
df_copy.columns

Index(['match_id', 'innings', 'batting_team', 'bowling_team', 'over', 'ball',
       'ball_no', 'runs_target', 'toss_winner', 'toss_decision', 'venue',
       'city', 'overs', 'current_score', 'balls_bowled', 'wickets',
       'balls_left', 'runs_left', 'wickets_left', 'current_run_rate',
       'required_run_rate', 'result'],
      dtype='object')

In [67]:
col_drop=['ball', 'ball_no','current_score', 'balls_bowled', 'wickets','innings']

In [68]:
df_copy.drop(columns=col_drop,inplace=True)

In [69]:
df_copy.head()

,match_id,batting_team,bowling_team,over,runs_target,toss_winner,toss_decision,venue,city,overs,balls_left,runs_left,wickets_left,current_run_rate,required_run_rate,result
124,335982,Royal Challengers Bangalore,Kolkata Knight Riders,0,223.0,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,20,119,222.0,10,6.0,11.19,0
125,335982,Royal Challengers Bangalore,Kolkata Knight Riders,0,223.0,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,20,119,221.0,10,12.0,11.14,0
126,335982,Royal Challengers Bangalore,Kolkata Knight Riders,0,223.0,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,20,118,221.0,10,6.0,11.24,0
127,335982,Royal Challengers Bangalore,Kolkata Knight Riders,0,223.0,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,20,117,220.0,10,6.0,11.28,0
128,335982,Royal Challengers Bangalore,Kolkata Knight Riders,0,223.0,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,20,116,219.0,10,6.0,11.33,0

In [70]:
df_copy.batting_team.unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Mumbai Indians', 'Chennai Super Kings', 'Deccan Chargers',
       'Pune Warriors', 'Kochi Tuskers Kerala', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

In [71]:
teams=['Royal Challengers Bengaluru','Kolkata Knight Riders','Rajasthan Royals','Mumbai Indians','Chennai Super Kings','Sunrisers Hyderabad','Delhi Capitals', 'Punjab Kings', 'Gujarat Titans', 'Lucknow Super Giants']
df_copy=df_copy[df_copy['batting_team'].isin(teams)]
df_copy=df_copy[df_copy['bowling_team'].isin(teams)]
df_copy=df_copy[df_copy['toss_winner'].isin(teams)]

In [72]:
df_copy['toss_advantage'] = (df_copy['toss_winner'] == df_copy['batting_team']).astype(int)

In [73]:
df_copy.drop('toss_winner',inplace=True,axis=1)

In [74]:
df_copy.tail()

,match_id,batting_team,bowling_team,over,runs_target,toss_decision,venue,city,overs,balls_left,runs_left,wickets_left,current_run_rate,required_run_rate,result,toss_advantage
278199,1473511,Punjab Kings,Royal Challengers Bengaluru,19,191.0,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,20,5,29.0,3,8.45,34.8,0,1
278200,1473511,Punjab Kings,Royal Challengers Bengaluru,19,191.0,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,20,4,29.0,3,8.38,43.5,0,1
278201,1473511,Punjab Kings,Royal Challengers Bengaluru,19,191.0,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,20,3,23.0,3,8.62,46.0,0,1
278202,1473511,Punjab Kings,Royal Challengers Bengaluru,19,191.0,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,20,2,19.0,3,8.75,57.0,0,1
278203,1473511,Punjab Kings,Royal Challengers Bengaluru,19,191.0,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,20,1,13.0,3,8.97,78.0,0,1

In [37]:
df_copy.to_csv('IPL_cleaned_dataset.csv')

In [75]:
df_copy.isnull().sum()

match_id             0
batting_team         0
bowling_team         0
over                 0
runs_target          0
toss_decision        0
venue                0
city                 0
overs                0
balls_left           0
runs_left            0
wickets_left         0
current_run_rate     0
required_run_rate    0
result               0
toss_advantage       0
dtype: int64

In [76]:
df_copy=df_copy[df_copy['balls_left']>30]

In [77]:
df_copy=df_copy[df_copy['required_run_rate']<30]

In [78]:
df_copy.to_csv('IPL_cleaned_dataset1.csv')